spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: ${DB_PASSWORD:postgres}
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:test_graphql_db}
        username: ${DB_USERNAME:postgres}
    graphql:
        graphiql:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    sql:
        init:
            mode: always